### ISSUE TITLE
Elaborar um DIAGRAMA DE IMPLANTAÇÃO (DEPLOYMENT DIAGRAM) da solução.

### ISSUE THREAD

**Issue by tmsasaki** [rafaelalgsantos/ppads-projeto-05j-2018s2#9]

**Comment by rickpizz** [comment]
![deploymentdiagram](https://user-images.githubusercontent.com/28661500/48371919-2daae680-e6a4-11e8-94a1-e591c1e359eb.png)

**Comment by tmsasaki** [comment]
Adicionar no diagrama os componentes instalados em cada servidor (por exemplo, Node JS, Mongo DB etc.).

**Comment by rafaela-guimaraes** [comment]
Feito, professor, poderia verificar?
